### ISSUE TITLE
How to use on functions?

### ISSUE THREAD

**Issue by huseinzol05** [bwohlberg/jonga#2]
Let say I have a very simple program,

```python
from IPython.display import SVG
import jonga

def step(x):
    return x + 1

ct = jonga.CallTracer(srcmodflt='[^IPython]', grpflt='^[^\.]*')

ct.start()
step(2)
ct.stop()

g = ct.graph(fntsz=10, fntfm=fntfm)

SVG(g.draw(format='svg'))
```

It returns empty SVG. I have a code that very deep in functions dependencies.

**Comment by bwohlberg** [comment]
Your example generates a null call graph because the traced function doesn't call any other functions. If you replace ``step`` with
```
def step_a(x):
    return step_b(x)

def step_b(x):
    return x + 1
```
and trace ``step_a``
```
ct.start()
step_a(2)
ct.stop()
```
the call graph consists of the call from ``step_a`` to ``step_b``, which can be confirmed by printing a string representation of the call tracer object
```
print(ct)
```

By the way, you can also use a context manager syntax
```
with jonga.ContextCallTracer(ct):
    step_a(2)
```
instead of calling the ``start`` and ``stop`` methods of the call tracer object,.

**Comment by huseinzol05** [comment]
ok thanks! understood.
